### ISSUE TITLE
update 26 Oct 2024, dont use this with LockDown Browser

### ISSUE THREAD

**Issue by heroes1412** [Batlez/HiddenVM#18]
Lockdown Brower can detect this antidetect :), be careful

![image](https://github.com/user-attachments/assets/5c4013ac-4dab-4a8f-8a83-85c9506cd8c2)

Maybe antidetect v7 (date 2023) can bypass it ( but cracker sell it with 70$)

**Comment by Batlez** [comment]
Did you follow all steps in the .txt file? Did you also configure your HiddenVM when you installed it?

**Comment by Batlez** [comment]
Lockdown Browser works completely fine still
![{2FB23916-1C75-475D-AF30-E0DBB5B93791}](https://github.com/user-attachments/assets/7988605c-111b-48ce-ae0a-086129d5de8f)

**Comment by Batlez** [comment]
When you make a virtual machine, you have to configure it as much as possible so it doesn't look like a virtual machine, like increasing processor cores, RAM, and GPU VRAM, and also make sure you have 70GB of storage or more, and it will be harder for proctoring softwares to detect if your using a virtual machine or not
