### ISSUE TITLE
issue after using rtsc

### ISSUE THREAD

**Issue by codebyjuan** [Batlez/HiddenVM#2]
![image](https://github.com/Batlez/HiddenVM/assets/162179915/d0479414-3fa6-4149-a29e-6aaf6f5f0e59)

**Comment by dev-nolant** [comment]
Same error as me

**Comment by Batlez** [comment]
Okay. I will fix the RTSC.bat. Please download it from here again. I think I know what the issue is

**Comment by Batlez** [comment]
Please leave a comment here if you still get the same issue

**Comment by dev-nolant** [comment]
> Please leave a comment here if you still get the same issue

seems like it worked. Launching software to test now
