### ISSUE TITLE
Any user Instructions on how to use it, even how how to start ?

### ISSUE THREAD

**Issue by nowhere-girl** [Batlez/HiddenVM#3]
I came across this repo but there is no instruction on how to use this. Will this work with vmware ? My host is Linux and my vmware client is win10. There is no vboxmanage.exe in my host system. Or does this only work with the one from Viktor ? For those who are not familiar with this field, there so much confusion.

**Comment by Batlez** [comment]
There is a text file when you download it to help understand it better. Please download the zip file here: https://github.com/Batlez/HiddenVM/releases/tag/1

**Comment by ReddoMaou** [comment]
> There is a text file when you download it to help understand it better. Please download the zip file here: https://github.com/Batlez/HiddenVM/releases/tag/1

Bud we are going to need exact instructions, your "read this first" file doesn't mean anything to anyone.

for example, if I were to use regular Vbox I would have multiple options for operating systems this "guide" implies that it works with a Windows VM BUT you only seem to have one choice of OS being Whonix(whatever the hell that is) when creating a VM through it, was I meant to have a VM ready to go and load into the software beforehand? if not where are my OS options? why are there so many errors?

Dont get me wrong I am grateful but I would be more so if I knew how to actually use this properly.

**Comment by Batlez** [comment]
> > There is a text file when you download it to help understand it better. Please download the zip file here: https://github.com/Batlez/HiddenVM/releases/tag/1
> 
> Bud we are going to need exact instructions, your "read this first" file doesn't mean anything to anyone.
> 
> for example, if I were to use regular Vbox I would have multiple options for operating systems this "guide" implies that it works with a Windows VM BUT you only seem to have one choice of OS being Whonix(whatever the hell that is) when creating a VM through it, was I meant to have a VM ready to go and load into the software beforehand? if not where are my OS options? why are there so many errors?
> 
> Dont get me wrong I am grateful but I would be more so if I knew how to actually use this properly.

If you have an issue, please open a ticket
