### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by Ridnr** [Batlez/HiddenVM#6]
Can you please do step by step instructions

**Comment by Ridnr** [comment]
dose it work with LockDown Browser the recent update 2.1.2.06?

**Comment by Batlez** [comment]
Yes it should work with Lockdown Browser version 2.1.2. Please let me  know if you run into any issues

**Comment by Batlez** [comment]
> do you have any updates?. i see the newer version has many modification mod

If you can find me the installer, sure

**Comment by heroes1412** [comment]
> > do you have any updates?. i see the newer version has many modification mod
> 
> If you can find me the installer, sure

do you use telegram or something, i will send you download link (2023 version, need key)

**Comment by Batlez** [comment]
> > > do you have any updates?. i see the newer version has many modification mod
> > 
> > 
> > If you can find me the installer, sure
> 
> do you use telegram or something, i will send you download link (2023 version, need key)

Please add me on Discord: Croakq
And send it to me and I will make sure everything works

**Comment by heroes1412** [comment]
i just sent you friend request, I have never used discord before, dont know how to send direct message to you :D
my discord: hoangtran1908
