### ISSUE TITLE
Unable to read extension pack

### ISSUE THREAD

**Issue by JoeTrannOP** [Batlez/HiddenVM#9]
Hi, firstly thanks for your amazing project which is completely free. 
I have a problem installing extension pack
I keep getting this error
![image](https://github.com/user-attachments/assets/361a7273-dd90-41c9-8292-65e30ee23b70)

**Comment by Batlez** [comment]
You need to uninstall VM virtual box, and instead install the the .exe from the .zip
https://github.com/Batlez/HiddenVM/releases/download/1/HiddenVM.zip
